name: m_flow
description: "Markdown Document Writer."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  html: ^0.15.4
  markdown: ^7.2.2
  pdf: ^3.11.0
  printing: ^5.13.1
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  flutter_math_fork: ^0.7.2
  screenshot: ^3.0.0
  window_manager: ^0.3.9
  http: ^1.2.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_oss_licenses: ^3.0.2

flutter:
  uses-material-design: true


assets:
  trim: "assets/fonts/trim/trim.ttf"
  rustic: "assets/fonts/RusticBlackShadow/RusticBlackShadow.ttf"
  githubTheme: "assets/themes/github.json"